apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: krm-deployment-test
  name: krm-deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: krm-deployment-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: krm-deployment-test
    spec:
      containers:
        - image: nginx
          name: nginx
          resources: {}
status: {}
